button_width = 400;
button_height = 100;
x = 960;
y = 540;
cost = 100;
pack_size = 5;
last_pack_names = [];
pack_timer = 0;
p_upgrade_rare = 0.20;
p_upgrade_epic = 0.08;
p_upgrade_legendary = 0.02;
confirm_open = false;
reveal_active = false;
reveal_cards = [];
reveal_index = 0;
reveal_anim_t = 0;
reveal_t = 0;
reveal_stage = 0; // 0: slide-in, 1: flip, 2: hold
reveal_face = 1;  // 1: back, 0: front
portal_scale = 0;
portal_state = 0; // 0 idle, 1 grow, 6 shrink
reveal_sequence = false;
reveal_ready = false;
reveal_wait_frames = round(room_speed * 1.3);
portal_done = false;
loading_active = false;
loading_timer = 0;
loading_angle = 0;
loading_idx = 0;
loading_elapsed = 0;
loading_min_frames = round(room_speed * 0.7);
buy_quantity = 1;
buy_qty_edit_mode = false;
buy_qty_input = "";
